import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  GITHUB_WORKFLOW_PATH,
  initGitHubCi,
} from "../src/init-ci.js";

const temporaryRoots: string[] = [];

afterEach(async () => {
  await Promise.all(
    temporaryRoots.splice(0).map((root) => rm(root, { recursive: true })),
  );
});

async function fixture(
  agents: Record<string, unknown> = {
    agent: { command: "codex", args: [], promptMode: "stdin" },
    authorAgent: { command: "cline", args: [], promptMode: "stdin" },
    validatorAgent: { command: "claude", args: [], promptMode: "stdin" },
  },
): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "program-pipeline-ci-"));
  temporaryRoots.push(root);
  await writeFile(
    join(root, "pipeline.config.json"),
    `${JSON.stringify(
      {
        schemaVersion: 1,
        pipelineVersion: "0.12.3",
        visionPath: "docs/vision.md",
        requireApprovalBeforeBuild: true,
        models: {},
        verify: {},
        contextDocs: [],
        ...agents,
      },
      null,
      2,
    )}\n`,
    "utf8",
  );
  return root;
}

describe("initGitHubCi", () => {
  it("creates a manual, concurrent-safe GitHub workflow for configured CLIs", async () => {
    const root = await fixture();
    await writeFile(join(root, "package.json"), "{}\n", "utf8");
    await writeFile(join(root, "package-lock.json"), "{}\n", "utf8");

    const result = await initGitHubCi({ cwd: root, force: false });

    expect(result.result).toBe("created");
    expect(result.agents).toEqual(["codex", "cline", "claude"]);
    expect(result.requiredVariables).toEqual(
      expect.arrayContaining([
        "CODEX_VERSION",
        "CLINE_VERSION",
        "CLAUDE_CODE_VERSION",
      ]),
    );
    const workflow = await readFile(join(root, GITHUB_WORKFLOW_PATH), "utf8");
    expect(workflow).toContain("workflow_dispatch:");
    expect(workflow).toContain("group: program-pipeline-");
    expect(workflow).toContain("PIPELINE_BRANCH: program/");
    expect(workflow).toContain("          npm ci");
    expect(workflow).toContain('"@openai/codex@$CODEX_VERSION"');
    expect(workflow).toContain('"cline@$CLINE_VERSION"');
    expect(workflow).toContain(
      '"@anthropic-ai/claude-code@$CLAUDE_CODE_VERSION"',
    );
    expect(workflow).toContain("aws-actions/configure-aws-credentials@v4");
    expect(workflow).toContain(
      'npm install --global "@wildorder/program-pipeline@0.12.3"',
    );
    expect(workflow).toContain('program-pipeline "${args[@]}"');
    expect(workflow).toContain("steps.checkpoint.outputs.has_changes == 'true'");
    expect(workflow).toContain('if [[ "$code" == "2" ]]');
    expect(workflow).not.toContain("cache: npm");
  });

  it("preserves an existing workflow unless force is explicit", async () => {
    const root = await fixture();
    const first = await initGitHubCi({ cwd: root, force: false });
    await writeFile(join(root, first.path), "authored workflow\n", "utf8");

    const skipped = await initGitHubCi({ cwd: root, force: false });
    expect(skipped.result).toBe("skipped");
    await expect(readFile(join(root, first.path), "utf8")).resolves.toBe(
      "authored workflow\n",
    );
    expect(skipped.requiredVariables).toContain("CODEX_VERSION");

    const replaced = await initGitHubCi({ cwd: root, force: true });
    expect(replaced.result).toBe("updated");
    await expect(readFile(join(root, first.path), "utf8")).resolves.toContain(
      "Generated by @wildorder/program-pipeline",
    );
  });

  it("installs a CLI used only by the recovery agent", async () => {
    const root = await fixture({
      agent: { command: "codex" },
      recoveryAgent: { command: "claude" },
      authorAgent: { command: "codex" },
      validatorAgent: { command: "codex" },
    });

    const result = await initGitHubCi({ cwd: root, force: false });

    expect(result.agents).toEqual(["codex", "claude"]);
    const workflow = await readFile(join(root, result.path), "utf8");
    expect(workflow).toContain(
      '"@anthropic-ai/claude-code@$CLAUDE_CODE_VERSION"',
    );
  });

  it("uses an explicit setup command and warns about unknown agent commands", async () => {
    const root = await fixture({
      agent: {
        command: "/opt/agents/custom-agent.exe",
        args: [],
        promptMode: "stdin",
      },
    });
    await writeFile(join(root, "package.json"), "{}\n", "utf8");
    await writeFile(join(root, "bun.lock"), "", "utf8");

    const result = await initGitHubCi({
      cwd: root,
      force: false,
      setupCommand: "make bootstrap",
    });

    expect(result.warnings).toContain(
      'Agent command "custom-agent" is not installed by the generated workflow; add its setup step manually.',
    );
    const workflow = await readFile(join(root, result.path), "utf8");
    expect(workflow).toContain("make bootstrap");
    expect(workflow).not.toContain("oven-sh/setup-bun");
    expect(workflow).not.toContain("Install configured agent CLIs");
  });

  it("requires a valid initialized pipeline configuration", async () => {
    const root = await mkdtemp(join(tmpdir(), "program-pipeline-ci-"));
    temporaryRoots.push(root);

    await expect(
      initGitHubCi({ cwd: root, force: false }),
    ).rejects.toThrow("run program-pipeline init first");

    await writeFile(join(root, "pipeline.config.json"), "{}\n", "utf8");
    await expect(
      initGitHubCi({ cwd: root, force: false }),
    ).rejects.toThrow("pipeline.config.json is invalid");
  });

  it("rejects a malformed recovery agent configuration", async () => {
    const root = await fixture({ recoveryAgent: { args: [] } });

    await expect(
      initGitHubCi({ cwd: root, force: false }),
    ).rejects.toThrow("recoveryAgent.command");
  });
});
